/** SHΞN Studio runtime for Android. */
import { AndroidFetch, AndroidStorage } from "./android-bridge-shim.js";

const STORAGE_KEY = "shen_studio_config";
const STYLE_ID = "bds-studio-runtime-style";
const PROCESSED_ATTR = "data-bds-studio-processed";
const DEFAULT_PROXY_URL = "https://superscrap.shervin003254024.workers.dev/";
const BDS_SETTINGS_KEY = "bds_settings";
const BDS_MCP_SERVERS_KEY = "bds_mcp_servers";
const BDS_API_KEYS_KEY = "bds_api_playground_keys";

const DEFAULT_CONFIG = {
  github: { owner: "", token: "", server: "https://api.github.com" },
  cloudflare: { accountId: "", token: "", zoneId: "", workerProxyUrl: DEFAULT_PROXY_URL },
  deepseek: { key: "", model: "deepseek-chat" },
  gemini: { key: "", model: "gemini-2.0-flash" },
  openai: { key: "", model: "gpt-4o-mini", base: "https://api.openai.com/v1" },
  anthropic: { key: "", model: "claude-3-5-sonnet-latest" },
  custom: [], workers: [], misc: {},
};

let scanTimer = 0, menuTimer = 0, modalRoot = null, settingsRoot = null;

export function initStudioRuntime() {
  if (typeof window === "undefined" || window.__bdsStudioRuntimeInstalled) return;
  window.__bdsStudioRuntimeInstalled = true;
  installStyles(); installBridge(); migrateAppSettingsIntoStudio(); installPromptInjector(); scheduleStudioScan(); scheduleMenuInject(); syncStudioToApp(getStudioConfig());
  new MutationObserver(() => { scheduleStudioScan(); scheduleMenuInject(); }).observe(document.documentElement, { childList: true, subtree: true, characterData: true });
  window.addEventListener("bds:urlChanged", () => { scheduleStudioScan(); scheduleMenuInject(); });
  window.addEventListener("bds:open-studio-settings", openSettings);
}

function installBridge() {
  window.StudioBridge = {
    getConfig: () => getStudioConfig(), getPublicConfig: () => getStudioConfig(),
    setConfig(config) { setStudioConfig(config); return true; },
    async fetch(payload) { return studioFetch(payload || {}); },
    async proxyFetch(url, options) { return studioProxyFetch(url, options || {}); },
    async github(path, options) { const cfg=getStudioConfig(); return studioFetch(withAuth((cfg.github?.server || "https://api.github.com").replace(/\/$/, "") + normalizeApiPath(path), options || {}, "github", cfg)); },
    async cloudflare(path, options) { return studioFetch(withAuth("https://api.cloudflare.com/client/v4" + normalizeApiPath(path), options || {}, "cloudflare")); },
    async deepseek(prompt, model) { return callOpenAiCompatible("deepseek", "https://api.deepseek.com/chat/completions", prompt, model); },
    async openai(prompt, model) { return callOpenAiCompatible("openai", "https://api.openai.com/v1/chat/completions", prompt, model); },
    async gemini(prompt, model) { return callGemini(prompt, model); },
    onResult(payload) { window.dispatchEvent(new CustomEvent("bds:studio-result", { detail: payload })); return true; },
  };
}

function normalizeApiPath(path) { const s = String(path || ""); if (/^https?:\/\//i.test(s)) return s.replace(/^https?:\/\/[^/]+/i, ""); return s.startsWith("/") ? s : `/${s}`; }
async function studioFetch(payload) { const cfg = getStudioConfig(); const direct = await AndroidFetch.send({ type: "bds-fetch-url", ...payload }); if (direct?.ok) return direct; if (cfg.cloudflare?.workerProxyUrl) { const proxied = await studioProxyFetch(payload.url, payload.options || {}, direct?.error); if (proxied?.ok) return proxied; } return direct; }
async function studioProxyFetch(url, options = {}, previousError = "") { const proxy = getStudioConfig().cloudflare?.workerProxyUrl || DEFAULT_PROXY_URL; if (!proxy || !url) return { ok: false, error: previousError || "No proxy/url configured" }; const sep = proxy.includes("?") ? "&" : "?"; return AndroidFetch.send({ type: "bds-fetch-url", url: `${proxy}${sep}url=${encodeURIComponent(String(url))}`, options: { method: "GET", ...(options || {}) } }); }
function withAuth(url, options, service, cfg = getStudioConfig()) { const token = service === "cloudflare" ? cfg.cloudflare?.token : cfg.github?.token; const headers = { ...(options.headers || {}) }; if (token) headers.Authorization = `Bearer ${token}`; if (service === "github") { headers.Accept ||= "application/vnd.github+json"; headers["X-GitHub-Api-Version"] ||= "2022-11-28"; } if (service === "cloudflare") headers["Content-Type"] ||= "application/json"; return { url, options: { ...options, headers } }; }
async function callOpenAiCompatible(service, defaultUrl, prompt, model) { const cfg = getStudioConfig()[service] || {}; const key = cfg.key || cfg.token || ""; const url = cfg.base ? `${String(cfg.base).replace(/\/$/, "")}/chat/completions` : defaultUrl; return studioFetch({ url, options: { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` }, body: JSON.stringify({ model: model || cfg.model, messages: [{ role: "user", content: prompt }] }) } }); }
async function callGemini(prompt, model) { const cfg = getStudioConfig().gemini || {}; const m = model || cfg.model || "gemini-2.0-flash"; return studioFetch({ url: "https://generativelanguage.googleapis.com/v1beta/models/" + encodeURIComponent(m) + ":generateContent?key=" + encodeURIComponent(cfg.key || ""), options: { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }) } }); }

function getStudioConfig() { const stored = AndroidStorage.get(STORAGE_KEY); return mergeConfig(DEFAULT_CONFIG, stored && typeof stored === "object" ? stored : {}); }
function setStudioConfig(config) { const merged = mergeConfig(DEFAULT_CONFIG, config || {}); AndroidStorage.set(STORAGE_KEY, merged); try { localStorage.setItem(STORAGE_KEY, JSON.stringify(merged)); } catch {} syncStudioToApp(merged); window.dispatchEvent(new CustomEvent("bds:studio-config-changed", { detail: merged })); window.dispatchEvent(new CustomEvent("bds:request-config-push")); }
function mergeConfig(base, next) { return { ...base, ...next, github:{...base.github,...(next.github||{})}, cloudflare:{...base.cloudflare,...(next.cloudflare||{})}, deepseek:{...base.deepseek,...(next.deepseek||{})}, gemini:{...base.gemini,...(next.gemini||{})}, openai:{...base.openai,...(next.openai||{})}, anthropic:{...base.anthropic,...(next.anthropic||{})}, custom:Array.isArray(next.custom)?next.custom:base.custom, workers:Array.isArray(next.workers)?next.workers:base.workers, misc:next.misc&&typeof next.misc==="object"?next.misc:base.misc }; }
function migrateAppSettingsIntoStudio(){ try{ chrome.storage.local.get([BDS_SETTINGS_KEY], v=>{const s=v?.[BDS_SETTINGS_KEY]||{}; const cfg=getStudioConfig(); let changed=false; if(!cfg.github.token && s.githubToken){cfg.github.token=s.githubToken; changed=true;} if(changed) setStudioConfig(cfg);}); }catch{} }

function syncStudioToApp(cfg) {
  try {
    if (!window.chrome?.storage?.local || !cfg) return;
    const githubToken = String(cfg.github?.token || "").trim(), githubOwner = String(cfg.github?.owner || "").trim(), githubServer = String(cfg.github?.server || "https://api.github.com").trim();
    const deepseekKey = String(cfg.deepseek?.key || "").trim(), geminiKey = String(cfg.gemini?.key || "").trim(), openaiKey = String(cfg.openai?.key || "").trim(), cloudflareToken = String(cfg.cloudflare?.token || "").trim(), workerProxyUrl = String(cfg.cloudflare?.workerProxyUrl || "").trim();
    chrome.storage.local.get([BDS_SETTINGS_KEY, BDS_MCP_SERVERS_KEY, BDS_API_KEYS_KEY], (values) => {
      const settings = { ...(values?.[BDS_SETTINGS_KEY] || {}) };
      if (githubToken) settings.githubToken = githubToken;
      settings.githubServer = githubServer; settings.studioGithubOwner = githubOwner; settings.studioDeepSeekKey = deepseekKey; settings.studioGeminiKey = geminiKey; settings.studioOpenAiKey = openaiKey; settings.studioCloudflareToken = cloudflareToken; settings.studioWorkerProxyUrl = workerProxyUrl;
      const apiKeys = Array.isArray(values?.[BDS_API_KEYS_KEY]) ? [...values[BDS_API_KEYS_KEY]] : [];
      const keyUpsert = (id,name,key)=>{ if(!key) return; const i=apiKeys.findIndex(k=>k.id===id||k.name===name); const e={id,name,key,createdAt:Date.now()}; if(i>=0) apiKeys[i]={...apiKeys[i],...e}; else apiKeys.push(e); };
      keyUpsert("studio_github_token","GitHub",githubToken); keyUpsert("studio_deepseek_key","DeepSeek",deepseekKey); keyUpsert("studio_gemini_key","Gemini",geminiKey); keyUpsert("studio_openai_key","OpenAI",openaiKey); keyUpsert("studio_cloudflare_token","Cloudflare",cloudflareToken);
      const mcp = Array.isArray(values?.[BDS_MCP_SERVERS_KEY]) ? [...values[BDS_MCP_SERVERS_KEY]] : [];
      const upsert = (id, name, serverUrl, apiKey) => { if (!serverUrl || !apiKey || !/^https?:\/\//i.test(serverUrl)) return; const entry={id,name,serverUrl,apiKey,enabled:true,tools:[],createdAt:Date.now()}; const idx=mcp.findIndex(s=>s.id===id||s.name===name||s.serverUrl===serverUrl); if(idx>=0)mcp[idx]={...mcp[idx],...entry,tools:mcp[idx].tools||[]}; else mcp.push(entry); };
      upsert("studio_github_mcp", "GitHub MCP (Studio synced)", settings.githubMcpServerUrl || "", githubToken);
      chrome.storage.local.set({ [BDS_SETTINGS_KEY]: settings, [BDS_API_KEYS_KEY]: apiKeys, [BDS_MCP_SERVERS_KEY]: mcp }, () => { window.dispatchEvent(new CustomEvent("bds:settingsChanged")); window.dispatchEvent(new CustomEvent("bds:request-config-push")); });
      try { localStorage.setItem(BDS_API_KEYS_KEY, JSON.stringify(apiKeys)); } catch {}
    });
  } catch (e) { console.warn("[BDS Studio] sync failed", e); }
}

function buildStudioPrompt() { const rawCfg=getStudioConfig(); return ["[STUDIO_CONFIG]",JSON.stringify(rawCfg),"[/STUDIO_CONFIG]","","☬ SHΞN Studio is enabled and synced with BDS Advanced Settings → Integrations.","Read the user's saved client-side token from STUDIO_CONFIG / StudioBridge.getConfig(). GitHub token is also synced to bds_settings.githubToken and API Playground keys.","If GitHub token exists, treat GitHub as authenticated and use StudioBridge.github for repo/actions/commit tasks.","For real actions output a mobile dark <BDS:VISUALIZER> panel wired to StudioBridge APIs."].join("\n"); }
function installPromptInjector(){document.addEventListener("keydown",e=>{if(e.key!=="Enter"||e.shiftKey)return;const editor=findEditor(e.target);if(editor)prependPrompt(editor);},true);document.addEventListener("click",e=>{const btn=e.target?.closest?.('button, div[role="button"]');if(!btn||btn.closest("#bds-root"))return;if(/send/i.test(btn.getAttribute("aria-label")||btn.title||"")){const editor=document.querySelector("#chat-input, textarea[placeholder], [role='textbox'][contenteditable], .ProseMirror[contenteditable]");prependPrompt(editor);}},true)}
function findEditor(target){const el=target?.closest?.("#chat-input, textarea[placeholder], [role='textbox'][contenteditable], .ProseMirror[contenteditable]");return el&&!el.closest("#bds-root")?el:null} function getEditorText(el){return(el.tagName==="TEXTAREA"||el.tagName==="INPUT")?el.value:(el.textContent||"")} function setEditorText(el,text){if(!el)return;if(el.tagName==="TEXTAREA"||el.tagName==="INPUT")el.value=text;else el.textContent=text;el.dispatchEvent(new Event("input",{bubbles:true}))} function prependPrompt(editor){if(!editor)return;const text=getEditorText(editor);if(!text.trim()||text.includes("[STUDIO_CONFIG]"))return;setEditorText(editor,`${buildStudioPrompt()}\n\nUser prompt:\n${text}`)}
function scheduleMenuInject(){if(menuTimer)return;menuTimer=setTimeout(()=>{menuTimer=0;injectStudioMenuItem()},300)} function injectStudioMenuItem(){const drawer=document.querySelector("#bds-drawer .bds-drawer-body");if(!drawer||drawer.querySelector(".bds-studio-menu-item"))return;const section=document.createElement("div");section.className="bds-studio-menu-block";section.innerHTML=`<div class="bds-section-title"><span class="bds-icon-inline">☬</span> SHΞN Studio</div><button type="button" class="bds-featured-item bds-studio-menu-item"><span class="bds-cmd-icon">☬</span><span class="bds-cmd-info"><span class="bds-cmd-name">Studio Services</span><span class="bds-cmd-desc">Sync keys with Advanced Integrations, GitHub token and API Playground</span></span><span class="bds-cmd-usage">Open</span></button>`;section.querySelector("button")?.addEventListener("click",openSettings);drawer.insertBefore(section,drawer.firstChild)}
function scheduleStudioScan(){if(scanTimer)return;scanTimer=setTimeout(()=>{scanTimer=0;scanForPanels()},250)} function scanForPanels(){for(const node of document.querySelectorAll("div.ds-message, [data-message-author-role='assistant']")){if(node.getAttribute(PROCESSED_ATTR)==="1"||node.closest("#bds-root"))continue;const html=extractPanelHtml(node);if(!html)continue;node.setAttribute(PROCESSED_ATTR,"1");injectOpenButton(node,html);setTimeout(()=>openPanel(html),50)}} function extractPanelHtml(node){const text=node.textContent||"";const v=text.match(/<BDS:VISUALIZER>([\s\S]*?)<\/BDS:VISUALIZER>/i);if(v?.[1])return decodeHtmlEntities(v[1].trim());const f=text.match(/```html-panel\s*([\s\S]*?)```/i);if(f?.[1])return f[1].trim();return null} function decodeHtmlEntities(input){const t=document.createElement("textarea");t.innerHTML=input;return t.value} function injectOpenButton(messageNode,html){const host=document.createElement("div");host.className="bds-studio-card";host.innerHTML=`<div class="bds-studio-card-title">☬ SHΞN Studio panel</div><button type="button" class="bds-studio-open">Open Studio</button>`;host.querySelector("button")?.addEventListener("click",()=>openPanel(html));messageNode.appendChild(host)}
function openPanel(rawHtml){closePanel();const root=document.createElement("div");root.className="bds-studio-modal";root.innerHTML=`<div class="bds-studio-toolbar"><strong>☬ SHΞN Studio Terminal</strong><div><button type="button" class="bds-studio-config">Settings</button><button type="button" class="bds-studio-close">Close</button></div></div><iframe class="bds-studio-frame" allow="clipboard-read; clipboard-write; fullscreen; downloads" sandbox="allow-scripts allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-downloads allow-same-origin"></iframe>`;document.body.appendChild(root);modalRoot=root;root.querySelector(".bds-studio-close")?.addEventListener("click",closePanel);root.querySelector(".bds-studio-config")?.addEventListener("click",openSettings);root.querySelector("iframe").srcdoc=buildPanelDocument(rawHtml)} function closePanel(){modalRoot?.remove();modalRoot=null} function buildPanelDocument(html){const prelude=`<script>window.STUDIO_CONFIG=window.parent.StudioBridge.getConfig();window.StudioBridge=window.parent.StudioBridge;<\/script>`;return `${prelude}${html}`}
function openSettings(){closeSettings();const cfg=getStudioConfig();const root=document.createElement("div");root.className="bds-studio-settings";root.innerHTML=`<div class="bds-studio-settings-panel"><div class="bds-studio-settings-head"><strong>☬ Studio Services</strong><button type="button" data-close>×</button></div><label>GitHub owner<input data-k="github.owner" value="${esc(cfg.github.owner)}"></label><label>GitHub API server<input data-k="github.server" value="${esc(cfg.github.server)}"></label><label>GitHub token<input data-k="github.token" type="password" value="${esc(cfg.github.token)}"></label><label>Cloudflare API token<input data-k="cloudflare.token" type="password" value="${esc(cfg.cloudflare.token)}"></label><label>Worker proxy URL<input data-k="cloudflare.workerProxyUrl" value="${esc(cfg.cloudflare.workerProxyUrl)}"></label><label>DeepSeek key<input data-k="deepseek.key" type="password" value="${esc(cfg.deepseek.key)}"></label><label>Gemini key<input data-k="gemini.key" type="password" value="${esc(cfg.gemini.key)}"></label><label>OpenAI key<input data-k="openai.key" type="password" value="${esc(cfg.openai.key)}"></label><p>Save & Sync writes these values to Studio, Advanced Settings → Integrations GitHub token, API Playground keys, and client-side prompt config.</p><div class="bds-studio-settings-actions"><button type="button" data-save>Save & Sync</button></div></div>`;document.body.appendChild(root);settingsRoot=root;root.querySelector("[data-close]")?.addEventListener("click",closeSettings);root.querySelector("[data-save]")?.addEventListener("click",()=>{const next=getStudioConfig();for(const input of root.querySelectorAll("input[data-k]"))setDeep(next,input.dataset.k,input.value);setStudioConfig(next);closeSettings()})} function closeSettings(){settingsRoot?.remove();settingsRoot=null} function setDeep(obj,path,value){const parts=String(path).split(".");let cur=obj;while(parts.length>1){const p=parts.shift();cur[p]||={};cur=cur[p]}cur[parts[0]]=value} function esc(value){return String(value||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function installStyles(){if(document.getElementById(STYLE_ID))return;const style=document.createElement("style");style.id=STYLE_ID;style.textContent=`#bds-toggle .bds-main-logo{display:block;width:24px;height:24px;color:currentColor}.bds-studio-card{margin:12px 0;padding:12px;border:1px solid rgba(77,107,254,.25);border-radius:12px;background:rgba(15,15,15,.88);color:#d0d0d0;display:flex;gap:12px;align-items:center;justify-content:space-between}.bds-studio-open,.bds-studio-card button{border:0;border-radius:9px;padding:8px 12px;background:#4d6bfe;color:white}.bds-studio-modal{position:fixed;inset:0;z-index:2147483200;background:#050505;display:flex;flex-direction:column}.bds-studio-toolbar{height:50px;display:flex;align-items:center;justify-content:space-between;padding:0 12px;background:#0b0b0d;color:#eee;border-bottom:1px solid #222}.bds-studio-toolbar button{margin-left:8px;border:1px solid #333;border-radius:8px;background:#181818;color:#eee;padding:8px 10px}.bds-studio-frame{flex:1;border:0;width:100%;background:#0d0d0d}.bds-studio-settings{position:fixed;inset:0;z-index:2147483300;background:rgba(0,0,0,.62);display:flex;align-items:center;justify-content:center;padding:18px}.bds-studio-settings-panel{width:min(560px,100%);max-height:90vh;overflow:auto;background:#101014;color:#eee;border:1px solid #2a2a35;border-radius:16px;padding:16px}.bds-studio-settings-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.bds-studio-settings label{display:block;margin:10px 0;color:#aaa;font-size:12px}.bds-studio-settings input{width:100%;margin-top:5px;background:#08080a;color:#fff;border:1px solid #30303a;border-radius:8px;padding:10px}.bds-studio-settings p{color:#777;font-size:12px;line-height:1.6}.bds-studio-settings button{border:0;border-radius:9px;background:#4d6bfe;color:white;padding:8px 12px}`;document.documentElement.appendChild(style)}
